#! /bin/sh

OS_RELEASE_FILE=${OS_RELEASE_FILE:-/etc/os-release}
SUDO=`which sudo`

pkgs_common='
autoconf
automake
coreutils
git
gzip
make
tar
'

test -r $OS_RELEASE_FILE || exit

. $OS_RELEASE_FILE

case $ID in
    alpine)
        $SUDO apk update
        $SUDO apk add $pkgs_common
        ;;
    centos)
        case $VERSION_ID in
            8)
                extra_repos=powertools
                ;;
            9)
                extra_repos=crb
                ;;
        esac
        $SUDO dnf --assumeyes config-manager --set-enabled $extra_repos
        $SUDO dnf --assumeyes --refresh install epel-release epel-next-release
        $SUDO dnf --assumeyes --refresh install --allowerasing $pkgs_common
        ;;
    debian|ubuntu)
        $SUDO apt-get --assume-yes update
        $SUDO apt-get --assume-yes install $pkgs_common
        ;;
    fedora)
        $SUDO dnf --assumeyes --refresh install $pkgs_common
        ;;
    rhel)
        $SUDO dnf --assumeyes --refresh install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        $SUDO dnf --assumeyes --refresh install --allowerasing $pkgs_common
        ;;
esac
