#! /bin/sh

OS_RELEASE_FILE=${OS_RELEASE_FILE:-/etc/os-release}
SUDO=`which sudo`

pkgs_common='
autoconf
automake
coreutils
git
gzip
make
tar
'

test -r $OS_RELEASE_FILE || exit

. $OS_RELEASE_FILE

case $ID in
    alpine)
        $SUDO apk add $pkgs_common
        ;;
    centos)
        case $VERSION_ID in
            8)
                epel_repo=powertools
                pkgs_epel='
                epel-release
                epel-next-release
                '
                ;;
            9)
                epel_repo=crb
                pkgs_epel='
                https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/e/epel-release-9-2.el9.noarch.rpm
                https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/e/epel-next-release-9-2.el9.noarch.rpm
                '
                ;;
        esac
        $SUDO dnf --assumeyes config-manager --set-enabled $epel_repo
        $SUDO dnf --assumeyes install $pkgs_epel
        $SUDO dnf --assumeyes install --allowerasing $pkgs_common
        ;;
    fedora)
        $SUDO dnf --assumeyes install $pkgs_common
        ;;
    ubuntu)
        $SUDO apt-get --assume-yes install $pkgs_common
        ;;
esac
