#! /bin/sh

OS_RELEASE_FILE=${OS_RELEASE_FILE:-/etc/os-release}
SUDO=`which sudo`

pkgs_common='
cmake
clang
curl
findutils
gcc
grep
make
'

pkgs_alpine='
aws-cli
clang-extra-tools
ctags
g++
git-diff-highlight
less
python3-dev
py3-pip
vim
'

pkgs_centos='
clang-tools-extra
gcc-c++
platform-python-devel
python3-pip
vim-enhanced
'

pkgs_fedora='
awscli
clang-tools-extra
ctags
gcc-c++
python3-devel
python3-pip
vim-enhanced
'

pkgs_ubuntu='
awscli
clangd
exuberant-ctags
g++
python3-dev
python3-pip
vim
'

test -r $OS_RELEASE_FILE || exit

. $OS_RELEASE_FILE

case $ID in
    alpine)
        $SUDO apk add $pkgs_common $pkgs_alpine
        ;;
    centos)
        case $VERSION_ID in
            8)
                epel_repo=powertools
                pkgs_epel='
                epel-release
                epel-next-release
                '
                pkgs_centos="$pkgs_centos awscli ctags"
                ;;
            9)
                epel_repo=crb
                pkgs_epel='
                https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/e/epel-release-9-2.el9.noarch.rpm
                https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/e/epel-next-release-9-2.el9.noarch.rpm
                '
                ;;
        esac
        $SUDO dnf --assumeyes config-manager --set-enabled $epel_repo
        $SUDO dnf --assumeyes install $pkgs_epel
        $SUDO dnf --assumeyes install $pkgs_common $pkgs_centos
        case $VERSION_ID in
            9)
                $SUDO pip3 install --upgrade awscli
                ;;
        esac
        ;;
    fedora)
        $SUDO dnf --assumeyes install $pkgs_common $pkgs_fedora
        ;;
    ubuntu)
        $SUDO apt-get --assume-yes install $pkgs_common $pkgs_ubuntu
        ;;
esac
