#! /bin/sh

OS_RELEASE_FILE=${OS_RELEASE_FILE:-/etc/os-release}
SUDO=`which sudo`

pkgs_common='
cmake
clang
curl
findutils
gcc
grep
make
'

pkgs_alpine='
aws-cli
clang-extra-tools
ctags
g++
git-diff-highlight
less
linux-headers
python3-dev
py3-pip
vim
'

pkgs_centos='
awscli
clang-tools-extra
ctags
gcc-c++
platform-python-devel
python3-pip
vim-enhanced
'

pkgs_debian='
awscli
apt-utils
clangd
exuberant-ctags
g++
locales-all
python3-dev
python3-pip
vim-nox
'

pkgs_fedora='
awscli
clang-tools-extra
ctags
gcc-c++
python3-devel
python3-pip
vim-enhanced
'

pkgs_rhel='
clang-tools-extra
ctags
gcc-c++
platform-python-devel
python3-pip
vim-enhanced
'

test -r $OS_RELEASE_FILE || exit

. $OS_RELEASE_FILE

case $ID in
    alpine)
        $SUDO apk add $pkgs_common $pkgs_alpine
        ;;
    centos)
        case $VERSION_ID in
            8)
                extra_repos=powertools
                ;;
            9)
                extra_repos=crb
                ;;
        esac
        $SUDO dnf --assumeyes config-manager --set-enabled $extra_repos
        $SUDO dnf --assumeyes --refresh install epel-release epel-next-release
        $SUDO dnf --assumeyes --refresh install --allowerasing $pkgs_common $pkgs_centos
        ;;
    debian|ubuntu)
        $SUDO apt-get --assume-yes update
        $SUDO apt-get --assume-yes install $pkgs_common $pkgs_debian
        ;;
    fedora)
        $SUDO dnf --assumeyes --refresh install $pkgs_common $pkgs_fedora
        ;;
    rhel)
        $SUDO dnf --assumeyes --refresh install epel-release
        $SUDO dnf --assumeyes --refresh install --allowerasing $pkgs_common $pkgs_rhel
        $SUDO pip3 install awscli
        ;;
esac
