#! /bin/env bash

# functions

function usage()
{
	cat <<- eof

	Usage: $(basename $0) -v <version> [OPTIONS] <tool>

	  -v version
	  -p prefix
	  -e exec-prefix
	  -f extra configure flags
	  -j make jobs

	Examples:

	$(basename $0) -v 2.68 -p $HOME/usr -e $HOME/usr/$(arch) -j 4 autoconf

	eof
} # usage()

function cleanup()
{
  local dir=$1

  if [[ -d $dir ]]; then
    if rm -rf $dir; then
      echo "Removed $dir"
    else
      echo "Failed to clean $dir"
    fi
  fi
}

prefix=""
exec_prefix=""
flags=""
makejobs=""

while getopts "v:p:e:f:j:" opt; do
  case $opt in
    v ) version=$OPTARG ;;
    p ) prefix="--prefix=$OPTARG" ;;
    e ) exec_prefix="--exec-prefix=$OPTARG" ;;
    f ) flags="$flags $OPTARG" ;;
    j ) makejobs="--jobs=$OPTARG" ;;
    \? ) usage; exit 1 ;;
  esac
done

shift $(($OPTIND - 1))

if [[ -z $version ]]; then
  echo "Must specify version with -v"
  usage
  exit 1
fi

tool=$1

if [[ -z $tool ]]; then
  echo "Must specify tool argument"
  usage
  exit 1
fi

baseurl="http://ftp.gnu.org/gnu"

tmpdir=$(mktemp -d)

if ! pushd $tmpdir; then
  echo "Failed to create temporary directory"
  cleanup $tmpdir
  exit 1
fi

toolname="$tool-$version"
archive="$toolname.tar.gz"
signature="$archive.sig"
url="$baseurl/$tool/$archive"
signurl="$baseurl/$tool/$signature"

if ! wget $url; then
  echo "Failed to download $url"
  popd
  cleanup $tmpdir
  exit 1
fi

if ! wget $signurl; then
  echo "Failed to download $signurl"
  popd
  cleanup $tmpdir
  exit 1
fi

if ! gpg --keyserver-options auto-key-retrieve --verify $signature; then
  echo "Failed to verfiy signature $signature"
  popd
  cleanup $tmpdir
  exit 1
fi

if ! tar -xzf $archive; then
  echo "Failed to extract $archive"
  popd
  cleanup $tmpdir
  exit 1
fi

if ! pushd $toolname; then
  echo "Failed to change directory to $toolname"
  popd
  cleanup $tmpdir
  exit 1
fi

echo
echo "Running ./configure $prefix $exec_prefix $flags"
echo

if ! ./configure $prefix $exec_prefix $flags; then
  echo "Failed to configure $toolname"
  popd
  cleanup $tmpdir
  exit 1
fi

if ! make $makejobs; then
  echo "Failed to make $toolname"
  popd
  cleanup $tmpdir
  exit 1
fi

if ! make $makejobs install; then
  echo "Failed to install $toolname"
  popd
  cleanup $tmpdir
  exit 1
fi

popd

echo "Successfully installed $toolname"

popd
cleanup $tmpdir
