#! /bin/env bash

# functions

function usage()
{
	cat <<- eof

	Usage: $(basename $0) -v <version> [OPTIONS] <tool>

	  -v version
	  -p prefix
	  -e exec-prefix
	  -c extra configure flags
	  -C file with extra configure flags
	  -m extra make flags
	  -M file with extra make flags
	  -j make jobs

	Examples:

	$(basename $0) -v 2.68 -p $HOME/usr -e $HOME/usr/$(arch) -j 4 autoconf

	eof
} # usage()

function cleanup()
{
  local dir=$1

  if [[ -d $dir ]]; then
    if rm -rf $dir; then
      echo "Removed $dir"
    else
      echo "Failed to clean $dir"
    fi
  fi
}

prefix=""
exec_prefix=""
configflags=""
makeflags=""
makejobs=""

while getopts "v:p:e:c:C:m:M:j:" opt; do
  case $opt in
    v ) version=$OPTARG ;;
    p ) prefix="--prefix=$OPTARG" ;;
    e ) exec_prefix="--exec-prefix=$OPTARG" ;;
    c ) configflags="$configflags $OPTARG" ;;
    C ) configflags="$configflags $(cat $OPTARG | tr '\n' ' ')" ;;
    m ) makeflags="$makeflags $OPTARG" ;;
    M ) makeflags="$makeflags $(cat $OPTARG | tr '\n' ' ')" ;;
    j ) makejobs="--jobs=$OPTARG" ;;
    \? ) usage; exit 1 ;;
  esac
done

shift $(($OPTIND - 1))

if [[ -z $version ]]; then
  echo "Must specify version with -v"
  usage
  exit 1
fi

tool=$1

if [[ -z $tool ]]; then
  echo "Must specify tool argument"
  usage
  exit 1
fi

tmpdir=$(mktemp -d)

if ! pushd $tmpdir; then
  echo "Failed to create temporary directory"
  cleanup $tmpdir
  exit 1
fi

toolname="$tool-$version"
archive="$toolname.tar.gz"

if ! dl-gnu-tool -v $version $tool; then
  echo "Failed to download $tool"
  popd
  cleanup $tmpdir
  exit 1
fi

if ! tar -xzf $archive; then
  echo "Failed to extract $archive"
  popd
  cleanup $tmpdir
  exit 1
fi

if ! pushd $toolname; then
  echo "Failed to change directory to $toolname"
  popd
  cleanup $tmpdir
  exit 1
fi

echo
echo "Running ./configure $prefix $exec_prefix $configflags"
echo

if ! eval ./configure $prefix $exec_prefix $configflags; then
  echo "Failed to configure $toolname"
  popd
  cleanup $tmpdir
  exit 1
fi

echo
echo "Running make $makejobs $makeflags"
echo

if ! eval make $makejobs $makeflags; then
  echo "Failed to make $toolname"
  popd
  cleanup $tmpdir
  exit 1
fi

echo
echo "Running make $makejobs $makeflags install"
echo

if ! eval make $makejobs $makeflags install; then
  echo "Failed to install $toolname"
  popd
  cleanup $tmpdir
  exit 1
fi

popd

echo "Successfully installed $toolname"

popd
cleanup $tmpdir
