#! /bin/env bash

# functions

function usage()
{
	cat <<- eof

	Usage: $(basename $0) [OPTIONS]

	  -m m4 version
	  -c autoconf version
	  -k automake version
	  -l libtool version
	  -p prefix
	  -e exec-prefix
	  -f extra configure flags
	  -j make jobs

	Examples:

	$(basename $0) -m 1.4.16 -c 2.68 -k 1.11.1 -l 2.4 -p $HOME/usr

	eof
} # usage()

declare -A version

prefix=""
exec_prefix=""
flags=""
makejobs=""

while getopts "m:c:k:l:p:e:f:j:" opt; do
  case $opt in
    m ) version[m4]=$OPTARG ;;
    c ) version[autoconf]=$OPTARG ;;
    k ) version[automake]=$OPTARG ;;
    l ) version[libtool]=$OPTARG ;;
    p ) prefix="-p $OPTARG" ;;
    e ) exec_prefix="-e $OPTARG" ;;
    f ) flags="-f $OPTARG" ;;
    j ) makejobs="-j $OPTARG" ;;
    \? ) usage; exit 1 ;;
  esac
done

shift $(($OPTIND - 1))

for tool in m4 autoconf automake libtool; do

  if [[ -z ${version[$tool]} ]]; then
    continue
  fi

  if ! get-gnu-tool -v ${version[$tool]} $prefix $exec_prefix $flags $makejobs \
    $tool; then
    echo "Failed to install $tool"
    exit 1
  fi

  echo "Successfully installed $tool"
done
