#! /bin/env bash

# functions

function usage()
{
	cat <<- eof

	Usage: $(basename $0) [OPTIONS]

	  -v git version
	  -p prefix
	  -e exec-prefix
	  -f extra configure flags
	  -j make jobs
	  -b bash completion path

	Examples:

	$(basename $0) -v 1.7.4.1 -p $HOME/usr -e $HOME/usr/$(arch)

	eof
} # usage()

function cleanup()
{
  local dir=$1

  if [[ -d $dir ]]; then
    if rm -rf $dir; then
      echo "Removed $dir"
    else
      echo "Failed to clean $dir"
    fi
  fi
}

prefix=""
exec_prefix=""
flags=""
makejobs=""
bashcomp=""
srcbashcomp="contrib/completion/git-completion.bash"

while getopts "v:p:e:f:j:b:" opt; do
  case $opt in
    v ) version=$OPTARG ;;
    p ) prefix="--prefix=$OPTARG" ;;
    e ) exec_prefix="--exec-prefix=$OPTARG" ;;
    f ) flags="$flags $OPTARG" ;;
    j ) makejobs="--jobs=$OPTARG" ;;
    b ) bashcomp=$OPTARG ;;
    \? ) usage; exit 1 ;;
  esac
done

shift $(($OPTIND - 1))

if [[ -z $version ]]; then
  echo "Must specify version with -v"
  usage
  exit 1
fi

baseurl="http://www.kernel.org/pub/software/scm"

tmpdir=$(mktemp -d)

if ! pushd $tmpdir; then
  echo "Failed to create temporary directory"
  cleanup $tmpdir
  exit 1
fi

tool="git"
toolname="$tool-$version"
archive="$toolname.tar.bz2"
signature="$archive.sign"
url="$baseurl/$tool/$archive"
signurl="$baseurl/$tool/$signature"

if ! wget $url; then
  echo "Failed to download $url"
  popd
  cleanup $tmpdir
  exit 1
fi

if ! wget $signurl; then
  echo "Failed to download $signurl"
  popd
  cleanup $tmpdir
  exit 1
fi

if ! gpg --verify $signature $archive; then
  echo "Failed to verfiy signature $signature"
  popd
  cleanup $tmpdir
  exit 1
fi

if ! tar -xjf $archive; then
  echo "Failed to extract $archive"
  popd
  cleanup $tmpdir
  exit 1
fi

if ! pushd $toolname; then
  echo "Failed to change directory to $toolname"
  popd
  cleanup $tmpdir
  exit 1
fi

echo "Running ./configure $prefix $exec_prefix $flags"

if ! ./configure $prefix $exec_prefix $flags; then
  echo "Failed to configure $toolname"
  popd
  cleanup $tmpdir
  exit 1
fi

if ! make $makejobs; then
  echo "Failed to make $toolname"
  popd
  cleanup $tmpdir
  exit 1
fi

if ! make $makejobs install; then
  echo "Failed to install $toolname"
  popd
  cleanup $tmpdir
  exit 1
fi

if [[ -n $bashcomp ]]; then
  if ! install -vCT $srcbashcomp $bashcomp; then
    echo "Failed to install $srcbashcomp to $bashcomp"
  fi
fi

popd

if ! rm -rf $toolname $archive; then
  echo "Failed to clean $toolname"
  popd
  cleanup $tmpdir
  exit 1
fi

echo "Successfully installed $toolname"

popd
cleanup $tmpdir
