#! /bin/env bash

# functions

function usage()
{
	cat <<- eof 

	Usage: ${0##*/} [-p <port>] [-d <dir>]

	  -p device port
	  -d directory to place capture files

	Examples:

	   ${0##*/} -p usb0 -d /var/log/minicom

	eof
} # usage()

# constant variables

date_format="+%Y%m%d-%H%M%S"
suffix=".log"
options="--wrap"
port=""
directory=""

# process command line options
while getopts ":p:d:" opt; do
  case $opt in
    p ) port="$OPTARG";;
    d ) directory="$OPTARG";;
    \? ) usage; exit 1;;
  esac
done

shift $(($OPTIND - 1))

if [[ -z $port ]]; then

  echo "You must specify a port with -p"
  usage
  exit 1;
fi

if [[ -z $directory ]]; then

  echo "You must specify a log directory with -d"
  usage
  exit 1;
fi

if [[ ! -d $directory ]]; then

  echo "$directory is not a directory"
  usage
  exit 1;
fi

capturefile="${directory%/}/$port-$(date $date_format)$suffix"

options="$options --capturefile=$capturefile"

minicom $options $port
