#! /bin/env bash

action="mv"

usage="Usage: $0 [-c] -p <pattern> -r <replacement> <filename>..."

while getopts ":cp:r:" opt; do
  case $opt in
    c ) action="cp" ;;
    p ) pattern="$OPTARG" ;;
    r ) replacement="$OPTARG" ;;
    \? ) echo $usage; exit 1 ;;
  esac
done

shift $(($OPTIND - 1))

if [ -n "$pattern" ] && [ -n "$replacement" ]; then
  for filename in "$@"; do
    newfilename=${filename/$pattern/$replacement}
    $action $filename $newfilename
  done
else
  echo $usage
  exit 1
fi
