#! /bin/bash

# TODO parameterize these variables into command line options

user="detwiler"
user_home="/home/${user}"
remote_user="${user}"
logfile="${user_home}/usr/var/log/rbackup.log"

if ping -c 1 wolf &> /dev/null; then
  remote_host="wolf"
else
  remote_host="detnet.us"
fi

remote_dest="${user_home}/usr/var/archive/tiger"
dest="${remote_user}@${remote_host}:${remote_dest}"
options="--archive --cvs-exclude --compress --delete --log-file=${logfile}"

dir_list="Documents Mail Music Photos Pictures Public Templates Videos"

for dir in ${dir_list}; do

  src="${user_home}/${dir}"

  nice rsync ${options} ${src} ${dest}

done
