#! /bin/env bash

# functions

function usage()
{
	cat <<- eof

	Usage: $(basename $0) [OPTIONS] CITY

	  -f show forecast
	  -w show current weather

	Examples:

	$(basename $0) -f bmore
	$(basename $0) -w dc
	$(basename $0) -fw baltimore

	eof
} # usage()

while getopts ":fw" opt; do
  case ${opt} in
    f ) forecast_show="true" ;;
    w ) weather_show="true" ;;
    \? ) usage; exit 1 ;;
  esac
done

shift $((${OPTIND} - 1))

noaa="http://weather.noaa.gov/pub/data"
weather_dir="observations/metar/decoded"
forecast_dir="forecasts/zone"
noaa_weather="$noaa/$weather_dir"
noaa_forecast="$noaa/$forecast_dir"

weather_bmore="KDMH.TXT"
weather_bwi="KBWI.TXT"
weather_dc="KDCA.TXT"
weather_toledo="KTOL.TXT"
weather_cleveland="KCLE.TXT"

declare -A weather

weather[bmore]=$weather_bmore
weather[baltimore]=$weather_bmore
weather[bwi]=$weather_bwi
weather[dc]=$weather_dc
weather[dca]=$weather_dc
weather[toledo]=$weather_toledo
weather[cleveland]=$weather_cleveland

forecast_bmore="md/mdz011.txt"
forecast_dc="dc/dcz001.txt"
forecast_toledo="oh/ohz003.txt"
forecast_cleveland="oh/ohz010.txt"

declare -A forecast

forecast[bmore]=$forecast_bmore
forecast[baltimore]=$forecast_bmore
forecast[dc]=$forecast_dc
forecast[toledo]=$forecast_toledo
forecast[cleveland]=$forecast_cleveland

if [[ -z $@ ]]; then
  echo "Please enter a city name"
  usage
  exit 1
fi

if [[ -z $forecast_show && -z $weather_show ]]; then
  echo "Please specify a forecast and/or weather option"
  usage
  exit 1
fi

for city in "$@"; do

  if [[ -n $weather_show ]]; then
    echo
    if [[ -z ${weather[$city]} ]]; then
      echo "Unrecognized city name: $city"
      usage
      exit 1
    else
      url="$noaa_weather/${weather[$city]}"
      curl --silent $url
    fi
  fi

  if [[ -n $forecast_show ]]; then
    echo
    if [[ -z ${forecast[$city]} ]]; then
      echo "Unrecognized city name: $city"
      usage
      exit 1
    else
      url="$noaa_forecast/${forecast[$city]}"
      curl --silent $url | sed 's/\.\.\./\n/g; s/^\./\n/'
    fi
  fi

done
