name: ci
on: [push]
jobs:

  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}

    strategy:
      matrix:
        include:
          - image: alpine:latest
          - image: quay.io/centos/centos:centos7
          - image: quay.io/centos/centos:stream8
          - image: quay.io/centos/centos:stream9
          - image: debian:latest
          - image: fedora:latest
          - image: registry.access.redhat.com/ubi9/ubi
          - image: ubuntu:20.04
          - image: ubuntu:latest
          - image: ubuntu:rolling

    env:
      DEBIAN_FRONTEND: noninteractive
      GNULIB_REFDIR: "$HOME/.gnulib"
      GNULIB_URL: 'https://github.com/coreutils/gnulib.git'
      USER: ${{ github.repository_owner }}

    steps:
      - name: Upgrade Packages
        run: |
          . /etc/os-release
          case $ID in
              alpine) apk update && apk upgrade && apk add git tar;;
              centos)
                  case $VERSION_ID in
                        7) yum -y install dnf;;
                  esac
                  dnf -y upgrade && dnf -y install dnf-plugins-core git-core which
              ;;
              fedora|rhel) dnf -y upgrade && dnf -y install dnf-plugins-core git-core which;;
              debian|ubuntu) apt-get -y update && apt-get -y upgrade && apt-get -y install git;;
          esac

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # see: https://github.com/actions/checkout/issues/290
      - name: Fetch Tags
        run: |
          git config --global --add safe.directory $(pwd)
          git fetch --force --tags

      - name: Configure Gnulib Cache Key
        run: echo "GNULIB_CACHE_KEY=`git submodule status .gnulib | sed -re 's/^.([0-9,a-f]{1,}) .*$/\1/'`" >>$GITHUB_ENV

      - name: Cache Gnulib Repository
        id: cache-gnulib
        uses: actions/cache@v2
        env:
          cache-name: cache-gnulib
        with:
          path: ${{ env.GNULIB_REFDIR }}
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.GNULIB_CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Fetch Upstream Gnulib Repository
        if: steps.cache-gnulib.outputs.cache-hit != 'true'
        run: |
          if [ -d $GNULIB_REFDIR ]; then
              cd $GNULIB_REFDIR
              git pull --ff-only
          else
              git clone $GNULIB_URL $GNULIB_REFDIR
          fi

      - name: Bootstrap
        run: ./bootstrap --install-buildreqs --install-reqs

      - name: Configure
        run: ./configure --prefix=$RUNNER_TEMP/.local --sysconfdir=$RUNNER_TEMP/.config

      - name: Build
        run: make

      - name: Distribution Test
        run: make distcheck

      - name: Install
        run: make install

      - name: Integration Test
        run: |
          find $RUNNER_TEMP/.config/vim/$HOSTNAME/plugged/YouCompleteMe -name 'ycm_core*.so' | grep .

      - name: Configure Project Name and Version
        run: |
          echo "PROJECT_NAME=`cat .package-name`" >>$GITHUB_ENV
          echo "PROJECT_VERSION=`cat .version`" >>$GITHUB_ENV

      - name: Upload Distribution Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: distribution-artifacts
          if-no-files-found: error
          path: |
            ${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}.tar.gz
            .package-name
            .version

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download Distribution Artifacts
        uses: actions/download-artifact@v2
        with:
          name: distribution-artifacts

      - name: Configure Project Name and Version
        run: |
          echo "PROJECT_NAME=`cat .package-name`" >>$GITHUB_ENV
          echo "PROJECT_VERSION=`cat .version`" >>$GITHUB_ENV

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.PROJECT_VERSION }}
          release_name: Release ${{ env.PROJECT_VERSION }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}.tar.gz
          asset_name: ${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}.tar.gz
          asset_content_type: application/gzip
