name: cicd
on: [push]
jobs:
  cicd:
    name: CI/CD
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    strategy:
      matrix:
        image: ["alpine:latest", "fedora:latest"]
    env:
      CONAN_USERNAME: envconf
      GIT_AUTHOR_NAME: envconf
      GIT_AUTHOR_EMAIL: envconf@localhost
    steps:
      - name: Install Git
        run: |
          os_id=`sed -ne 's/^ID=//p' /etc/os-release`
          case $os_id in
              alpine) apk add git;;
              fedora) dnf --assumeyes install git-core which;;
          esac

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Requirements
        run: build-aux/install-reqs

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure --prefix=$RUNNER_TEMP/.local --sysconfdir=$RUNNER_TEMP/.config

      - name: Build
        run: make

      - name: Test
        run: make distcheck

      - name: Install
        run: make install

      - name: Integration Test
        run: vim -es -u $RUNNER_TEMP/.config/vim/vimrc -i NONE -c PlugInstall -c qa
