name: cicd
on: [push]
jobs:
  cicd:
    name: CI/CD
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: alpine:latest
            vim-ycm-owner: detwiler
            vim-ycm-ref: llvm-10
          - image: fedora:latest
            vim-ycm-owner: ycm-core
            vim-ycm-ref: master
    env:
      CONAN_USERNAME: envconf
      GIT_AUTHOR_NAME: envconf
      GIT_AUTHOR_EMAIL: envconf@localhost
      VIM_YCM_OWNER: ${{ matrix.vim-ycm-owner }}
      VIM_YCM_REF: ${{ matrix.vim-ycm-ref }}
    steps:
      - name: Upgrade Packages
        run: |
          os_id=`sed -ne 's/^ID=//p' /etc/os-release`
          case $os_id in
              alpine) apk update && apk upgrade && apk add git;;
              fedora) dnf --assumeyes upgrade && dnf --assumeyes install git-core which;;
          esac

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Requirements
        run: build-aux/install-reqs

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure --prefix=$RUNNER_TEMP/.local --sysconfdir=$RUNNER_TEMP/.config

      - name: Build
        run: make

      - name: Test
        run: make distcheck

      - name: Install
        run: make install

      - name: Integration Test
        run: |
          vim -es -u $RUNNER_TEMP/.config/vim/vimrc -i NONE -c PlugInstall -c qa
          find $RUNNER_TEMP/.config/vim/plugged/YouCompleteMe -name 'ycm_core.so' | grep .
