name: cicd
on: [push]
jobs:
  cicd:
    name: CI/CD
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: fedora:latest
            pkg-cmd: dnf --assumeyes install git-core which
          - image: alpine:latest
            pkg-cmd: apk add git
    env:
      CONAN_USERNAME: envconf
      GIT_AUTHOR_NAME: envconf
      GIT_AUTHOR_EMAIL: envconf@localhost
    steps:
      - name: Install Base Packages
        run: ${{ matrix.pgk-cmd }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Requirements
        run: build-aux/install-reqs

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: ./configure --prefix=$RUNNER_TEMP/.local --sysconfdir=$RUNNER_TEMP/.config

      - name: Build
        run: make

      - name: Test
        run: make distcheck

      - name: Install
        run: make install

      - name: Integration Test
        run: vim -es -u $RUNNER_TEMP/.config/vim/vimrc -i NONE -c PlugInstall -c qa
